#!/bin/bash

chunkc core::plugin_dir ~/.chunkwm_plugins
chunkc core::hotload 1

#
# NOTE: The following are config variables for the chunkwm-tiling plugin
#

chunkc set global_desktop_mode           bsp
chunkc set 2_desktop_mode                monocle
chunkc set 3_desktop_mode                float

chunkc set global_desktop_offset_top     10
chunkc set global_desktop_offset_bottom  10
chunkc set global_desktop_offset_left    10
chunkc set global_desktop_offset_right   10
chunkc set global_desktop_offset_gap     10

chunkc set 2_desktop_offset_top          190
chunkc set 2_desktop_offset_bottom       190
chunkc set 2_desktop_offset_left         190
chunkc set 2_desktop_offset_right        190

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           0
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

chunkc set preselect_border_color        0xfffdcc59
chunkc set preselect_border_width        4
chunkc set preselect_border_radius       4

#
# NOTE: The following are config variables for the chunkwm-border plugin
#

chunkc set focused_border_color          0xffdd464c
chunkc set focused_border_width          4
chunkc set focused_border_radius         4
chunkc set focused_border_skip_floating  1

#
# NOTE: The following are config variables for the chunkwm-transparency plugin
#

chunkc set window_fade_inactive          1
chunkc set window_fade_alpha             0.25
chunkc set window_fade_duration          0.1

#
# NOTE: specify plugins to load when chunkwm starts.
#       if chunkc plugin_dir is not set, the absolutepath is necessary.
#

chunkc core::load tiling.so
chunkc core::load border.so
# chunkc core::load transparency.so

#
# NOTE: shell commands require escaped quotes
#       to pass value containing a whitespace.
#

chunkc tiling::rule --owner Finder --name Copy --state float
chunkc tiling::rule --owner iTerm2 --name Hotkey Window --state float
chunkc tiling::rule --owner Twitter --state float
chunkc tiling::rule --owner qemu-system-x86_64 --desktop 2
chunkc tiling::rule --owner qemu-system-i386 --desktop 2

